pages:
  stage: deploy
  image: ruby:2.1
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc)
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
