image: ruby:2.3

variables:
  JEKYLL_ENV: gitlab

# jekyll-coffeescript need a JS runtime...
before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install nodejs -y
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --deployment --without development --full-index --retry 3 --clean

pages:
  stage: pages
  environment: production
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master

cache gems:
  script:
    - bundle package --all --all-platforms
  artifacts:
    paths:
      - vendor/cache
