image: ruby:2.3

variables:
  JEKYLL_ENV: gitlab

cache:
  key: "ruby-2.3"
  paths:
    - vendor/ruby

stages:
  - build
  - pages

# jekyll-coffeescript need a JS runtime...
before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install nodejs -y
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --deployment --without development --full-index --retry 3 --clean

build:
  stage: build
  script:
    - bundle exec jekyll build -d ./.public

pages:
  stage: pages
  environment: production
  script:
    - mv ./.public ./public
  artifacts:
    paths:
      - public
  only:
    - master
