# Site settings
title: "ChillCoding"
emails:
  company: "hello@chillcoding.com"
  macha: "macha@chillcoding.com"
  remy: "remy@chillcoding.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.chillcoding.com" # the base hostname & protocol for your site

# Blog
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: ':num'

google_analytics_id: UA-55688141-5
twitter_usernames:
  company: chillcodingnews
  remy: rymai
  macha: machaDaCosta
github_usernames:
  company: chillcoding-at-the-beach
  remy: rymai
  macha: machadaCosta
gitlab_usernames:
  company: chillcoding-at-the-beach
  remy: rymai
  macha: macha
usernames:
  remy: Rémy Coutable
  macha: Macha Da Costa

# Build settings, exclude vendor (this is where Gems are installed during CI build)
exclude: [CNAME, Gemfile, Gemfile.lock, README.md]
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
# These are the default on GitHub Pages:
# https://help.github.com/articles/configuring-jekyll/#defaults-you-can-change
kramdown:
  input: GFM
  hard_wrap: false
