# Site settings
title: "ChillCoding"
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.chillcoding.com" # the base hostname & protocol for your site

# Blog
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page-:num/"

google_analytics_id: UA-55688141-5
repository_url: https://gitlab.com/chillcoding-at-the-beach/chillcoding-at-the-beach.gitlab.io/

# Build settings, exclude vendor (this is where Gems are installed during CI build)
exclude: [CNAME, Gemfile, Gemfile.lock, README.md, serve, bachamada/README.md, bachamada/gruntfile.js, bachamada/package.json]
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
# These are the default on GitHub Pages:
# https://help.github.com/articles/configuring-jekyll/#defaults-you-can-change
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "homepage"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      layout: "post"
