# Site settings
title: "ChillCoding"
email: "contact@chillcoding.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chillcoding.com" # the base hostname & protocol for your site

google_analytics_id: UA-55688141-5
twitter_usernames:
  company: chillcodingnews
  remy: rymai
  macha: machaDaCosta
github_username: chillcoding-at-the-beach

# Build settings
exclude: [Gemfile, Gemfile.lock, README.md]
